version: "3"

volumes:
  mongo_data:
    driver: local
    external: false

services:
  mongo:
    image: mongo:4.0
    container_name: "mongo"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  mongo-express:
    image: mongo-express:latest
    container_name: "mongo-express"
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://root:password@db:27017"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: "redis-stack"
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
