version: "3"

volumes:
  mongo_data:
    driver: local
    external: false

networks:
  internal:
    external: false

services:
  mongo:
    image: mongo:4.0
    container_name: "mongo"
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - "internal"
    volumes:
      - "mongo_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  mongo-express:
    image: mongo-express:latest
    container_name: "mongo-express"
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - "internal"
    depends_on:
      - "mongo"
    environment:
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
      - "ME_CONFIG_MONGODB_AUTH_USERNAME=root"
      - "ME_CONFIG_MONGODB_AUTH_PASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017"
      - "ME_CONFIG_BASICAUTH=true"
      - "ME_CONFIG_BASICAUTH_USERNAME=root"
      - "ME_CONFIG_BASICAUTH_PASSWORD=password"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: "redis-stack"
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
