version: "3"

volumes:
  db_data:
    driver: local
    external: false

services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  admin:
    image: mongo-express:latest
    container_name: "mongoadmin"
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=password"
      - "ME_CONFIG_MONGODB_URL=mongodb://root:password@db:27017"
